### PR TITLE
V13 with Sets

### PR DESCRIPTION
**Pull request by steffen-hph**
Your current version for TYPO3 13 does not work for me. The typoscript is not loaded. 

Since I work with TYPO3 sets, I suspect that the ext_typoscript_setup.typoscript is no longer loaded automatically. 

Therefore I have changed it so that it works for me with sets and should also work without sets, but then with adding to the template. I don't know if this is the best solution for without sets.

### CODE REVIEW

**Comment by kitzberger** [comment]
@steffen-hph, thanks for this PR. Is it working on your 13 instance? Because on mine it isn't.

It's showing the new site set option and it can be included, yes. But I think its TypoScript/Yaml needs to be loaded globally in order to show the "message" field for the two finishers *EmailToSender* and *EmailToReceiver* in both form module and form plugins.

**Comment by kitzberger** [comment]
@steffen-hph, can you have a look at this one please? I've done some tiny changes to your patch. It's working now for me.

https://github.com/kitzberger/form-mailtext/pull/30

**Comment by steffen-hph** [comment]
@kitzberger, oh, sorry, I forgot that I had a bit more code due to the topic with https://github.com/kitzberger/form-mailtext/issues/19, which I didn't take in the PR. Thanks!

**Comment by kitzberger** [comment]
@steffen-hph, is #30 working for you too? Then I'll make another release for the extension...

**Comment by steffen-hph** [comment]
@kitzberger Yes #30 works for me too

**Pull request merged**
